INSERT INTO users (email, name, password) VALUES ("test@test.com", "testman", "Test1234!@");

INSERT INTO songs (title, singer, genre, description, like_count, play_count, user_id, created_at, updated_at) VALUES
    ('블루밍', '아이유', 0, '밝고 사랑스러운 K-POP 곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('Lemon', '요네즈 켄시', 1, '감성적인 J-POP 발라드입니다.', 0, 0, 1, NOW(), NOW()),
    ('모든 날 모든 순간', '폴킴', 2, '잔잔하고 따뜻한 감성의 발라드입니다.', 0, 0, 1, NOW(), NOW()),
    ('Smells Like Teen Spirit', 'Nirvana', 3, '90년대 록 음악을 대표하는 곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('강남스타일', '싸이', 4, '에너지 넘치는 댄스곡으로 전 세계를 사로잡은 히트곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('소주 한 잔', '임창정', 5, '애절한 감성의 트로트 발라드입니다.', 0, 0, 1, NOW(), NOW()),
    ('Dynamite', 'BTS', 0, '신나는 디스코 팝 스타일의 K-POP입니다.', 0, 0, 1, NOW(), NOW()),
    ('Pretender', 'Official髭男dism', 1, '일본 팝의 감성을 느낄 수 있는 곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('너를 만나', '폴킴', 2, '따뜻하고 잔잔한 발라드입니다.', 0, 0, 1, NOW(), NOW()),
    ('Bohemian Rhapsody', 'Queen', 3, '록 오페라의 전설적인 명곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('New Face', '싸이', 4, '익살스러운 분위기의 댄스곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('막걸리 한잔', '영탁', 5, '유쾌한 분위기의 트로트곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('그라데이션', '10CM', 2, '잔잔한 감성의 인디 발라드입니다.', 0, 0, 1, NOW(), NOW()),
    ('ON', 'BTS', 0, '에너제틱한 퍼포먼스 중심의 K-POP입니다.', 0, 0, 1, NOW(), NOW()),
    ('Paprika', 'Foorin', 1, '어린이와 어른 모두에게 친숙한 J-POP입니다.', 0, 0, 1, NOW(), NOW()),
    ('Hotel California', 'Eagles', 3, '미국 서부 록의 대표적인 곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('That That', '싸이', 4, '중독성 강한 댄스 트랙입니다.', 0, 0, 1, NOW(), NOW()),
    ('아모르 파티', '김연자', 5, '인생을 노래한 희망찬 트로트곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('봄날', 'BTS', 0, '그리움과 위로를 담은 K-POP입니다.', 0, 0, 1, NOW(), NOW()),
    ('한숨', '이하이', 2, '위로가 되는 소울풀한 발라드입니다.', 0, 0, 1, NOW(), NOW()),
    ('Love Dive', 'IVE', 0, '트렌디한 사운드의 K-POP 곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('Butter', 'BTS', 0, '부드럽고 중독성 있는 K-POP 트랙입니다.', 0, 0, 1, NOW(), NOW()),
    ('夜に駆ける', 'YOASOBI', 1, '몽환적인 분위기의 J-POP 곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('Shinunoga E-Wa', 'Fujii Kaze', 1, '개성 넘치는 멜로디의 일본 곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('비와 당신', '이승철', 2, '감성을 자극하는 발라드입니다.', 0, 0, 1, NOW(), NOW()),
    ('Tears', '소찬휘', 3, '폭발적인 고음의 록 발라드입니다.', 0, 0, 1, NOW(), NOW()),
    ('Bang Bang Bang', 'BIGBANG', 4, '강렬한 비트의 댄스곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('찐이야', '김호중', 5, '진심이 담긴 트로트곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('VVS', '미란이', 6, '힙합씬을 뒤흔든 감각적인 히트곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('Feeling Good', 'Nina Simone', 7, '클래식한 블루스 명곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('Eleven', 'IVE', 0, '신비로운 분위기의 K-POP 트랙입니다.', 0, 0, 1, NOW(), NOW()),
    ('Unholy', 'Sam Smith', 8, '장르 구분이 어려운 독특한 스타일입니다.', 0, 0, 1, NOW(), NOW()),
    ('사건의 지평선', '윤하', 2, '섬세한 감성의 록 발라드입니다.', 0, 0, 1, NOW(), NOW()),
    ('Still Life', 'BIGBANG', 3, '감성적인 록 기반의 K-POP입니다.', 0, 0, 1, NOW(), NOW()),
    ('Rock with you', '세븐틴', 0, '강렬한 록 사운드를 입힌 K-POP입니다.', 0, 0, 1, NOW(), NOW()),
    ('Permission to Dance', 'BTS', 4, '자유로운 느낌의 댄스 트랙입니다.', 0, 0, 1, NOW(), NOW()),
    ('회전목마', '릴보이', 6, '힙합과 트랩의 절묘한 조화입니다.', 0, 0, 1, NOW(), NOW()),
    ('Stormy Monday', 'T-Bone Walker', 7, '블루스의 고전적인 명곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('새삥', '지코', 6, '중독성 있는 힙합 사운드입니다.', 0, 0, 1, NOW(), NOW()),
    ('Cupid', 'FIFTY FIFTY', 0, '상큼한 감성의 K-POP 러브송입니다.', 0, 0, 1, NOW(), NOW()),
    ('Love Dive', 'IVE', 0, '트렌디한 사운드의 K-POP 곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('Butter', 'BTS', 0, '부드럽고 중독성 있는 K-POP 트랙입니다.', 0, 0, 1, NOW(), NOW()),
    ('夜に駆ける', 'YOASOBI', 1, '몽환적인 분위기의 J-POP 곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('Shinunoga E-Wa', 'Fujii Kaze', 1, '개성 넘치는 멜로디의 일본 곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('비와 당신', '이승철', 2, '감성을 자극하는 발라드입니다.', 0, 0, 1, NOW(), NOW()),
    ('Tears', '소찬휘', 3, '폭발적인 고음의 록 발라드입니다.', 0, 0, 1, NOW(), NOW()),
    ('Bang Bang Bang', 'BIGBANG', 4, '강렬한 비트의 댄스곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('찐이야', '김호중', 5, '진심이 담긴 트로트곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('VVS', '미란이', 6, '힙합씬을 뒤흔든 감각적인 히트곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('Feeling Good', 'Nina Simone', 7, '클래식한 블루스 명곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('Eleven', 'IVE', 0, '신비로운 분위기의 K-POP 트랙입니다.', 0, 0, 1, NOW(), NOW()),
    ('Unholy', 'Sam Smith', 8, '장르 구분이 어려운 독특한 스타일입니다.', 0, 0, 1, NOW(), NOW()),
    ('사건의 지평선', '윤하', 2, '섬세한 감성의 록 발라드입니다.', 0, 0, 1, NOW(), NOW()),
    ('Still Life', 'BIGBANG', 3, '감성적인 록 기반의 K-POP입니다.', 0, 0, 1, NOW(), NOW()),
    ('Rock with you', '세븐틴', 0, '강렬한 록 사운드를 입힌 K-POP입니다.', 0, 0, 1, NOW(), NOW()),
    ('Permission to Dance', 'BTS', 4, '자유로운 느낌의 댄스 트랙입니다.', 0, 0, 1, NOW(), NOW()),
    ('회전목마', '릴보이', 6, '힙합과 트랩의 절묘한 조화입니다.', 0, 0, 1, NOW(), NOW()),
    ('Stormy Monday', 'T-Bone Walker', 7, '블루스의 고전적인 명곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('새삥', '지코', 6, '중독성 있는 힙합 사운드입니다.', 0, 0, 1, NOW(), NOW()),
    ('Cupid', 'FIFTY FIFTY', 0, '상큼한 감성의 K-POP 러브송입니다.', 0, 0, 1, NOW(), NOW()),
    ('Love Dive', 'IVE', 0, '트렌디한 사운드의 K-POP 곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('Butter', 'BTS', 0, '부드럽고 중독성 있는 K-POP 트랙입니다.', 0, 0, 1, NOW(), NOW()),
    ('夜に駆ける', 'YOASOBI', 1, '몽환적인 분위기의 J-POP 곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('Shinunoga E-Wa', 'Fujii Kaze', 1, '개성 넘치는 멜로디의 일본 곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('비와 당신', '이승철', 2, '감성을 자극하는 발라드입니다.', 0, 0, 1, NOW(), NOW()),
    ('Tears', '소찬휘', 3, '폭발적인 고음의 록 발라드입니다.', 0, 0, 1, NOW(), NOW()),
    ('Bang Bang Bang', 'BIGBANG', 4, '강렬한 비트의 댄스곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('찐이야', '김호중', 5, '진심이 담긴 트로트곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('VVS', '미란이', 6, '힙합씬을 뒤흔든 감각적인 히트곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('Feeling Good', 'Nina Simone', 7, '클래식한 블루스 명곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('Eleven', 'IVE', 0, '신비로운 분위기의 K-POP 트랙입니다.', 0, 0, 1, NOW(), NOW()),
    ('Unholy', 'Sam Smith', 8, '장르 구분이 어려운 독특한 스타일입니다.', 0, 0, 1, NOW(), NOW()),
    ('사건의 지평선', '윤하', 2, '섬세한 감성의 록 발라드입니다.', 0, 0, 1, NOW(), NOW()),
    ('Still Life', 'BIGBANG', 3, '감성적인 록 기반의 K-POP입니다.', 0, 0, 1, NOW(), NOW()),
    ('Rock with you', '세븐틴', 0, '강렬한 록 사운드를 입힌 K-POP입니다.', 0, 0, 1, NOW(), NOW()),
    ('Permission to Dance', 'BTS', 4, '자유로운 느낌의 댄스 트랙입니다.', 0, 0, 1, NOW(), NOW()),
    ('회전목마', '릴보이', 6, '힙합과 트랩의 절묘한 조화입니다.', 0, 0, 1, NOW(), NOW()),
    ('Stormy Monday', 'T-Bone Walker', 7, '블루스의 고전적인 명곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('새삥', '지코', 6, '중독성 있는 힙합 사운드입니다.', 0, 0, 1, NOW(), NOW()),
    ('Cupid', 'FIFTY FIFTY', 0, '상큼한 감성의 K-POP 러브송입니다.', 0, 0, 1, NOW(), NOW()),
    ('Love Dive', 'IVE', 0, '트렌디한 사운드의 K-POP 곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('Butter', 'BTS', 0, '부드럽고 중독성 있는 K-POP 트랙입니다.', 0, 0, 1, NOW(), NOW()),
    ('夜に駆ける', 'YOASOBI', 1, '몽환적인 분위기의 J-POP 곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('Shinunoga E-Wa', 'Fujii Kaze', 1, '개성 넘치는 멜로디의 일본 곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('비와 당신', '이승철', 2, '감성을 자극하는 발라드입니다.', 0, 0, 1, NOW(), NOW()),
    ('Tears', '소찬휘', 3, '폭발적인 고음의 록 발라드입니다.', 0, 0, 1, NOW(), NOW()),
    ('Bang Bang Bang', 'BIGBANG', 4, '강렬한 비트의 댄스곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('찐이야', '김호중', 5, '진심이 담긴 트로트곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('VVS', '미란이', 6, '힙합씬을 뒤흔든 감각적인 히트곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('Feeling Good', 'Nina Simone', 7, '클래식한 블루스 명곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('Eleven', 'IVE', 0, '신비로운 분위기의 K-POP 트랙입니다.', 0, 0, 1, NOW(), NOW()),
    ('Unholy', 'Sam Smith', 8, '장르 구분이 어려운 독특한 스타일입니다.', 0, 0, 1, NOW(), NOW()),
    ('사건의 지평선', '윤하', 2, '섬세한 감성의 록 발라드입니다.', 0, 0, 1, NOW(), NOW()),
    ('Still Life', 'BIGBANG', 3, '감성적인 록 기반의 K-POP입니다.', 0, 0, 1, NOW(), NOW()),
    ('Rock with you', '세븐틴', 0, '강렬한 록 사운드를 입힌 K-POP입니다.', 0, 0, 1, NOW(), NOW()),
    ('Permission to Dance', 'BTS', 4, '자유로운 느낌의 댄스 트랙입니다.', 0, 0, 1, NOW(), NOW()),
    ('회전목마', '릴보이', 6, '힙합과 트랩의 절묘한 조화입니다.', 0, 0, 1, NOW(), NOW()),
    ('Stormy Monday', 'T-Bone Walker', 7, '블루스의 고전적인 명곡입니다.', 0, 0, 1, NOW(), NOW()),
    ('새삥', '지코', 6, '중독성 있는 힙합 사운드입니다.', 0, 0, 1, NOW(), NOW()),
    ('Cupid', 'FIFTY FIFTY', 0, '상큼한 감성의 K-POP 러브송입니다.', 0, 0, 1, NOW(), NOW());